-- MySQL Script generated by MySQL Workbench
-- Fri Dec 15 16:54:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`Banker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Banker` (
  `idBanker` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idBanker`),
  UNIQUE INDEX `idBanker_UNIQUE` (`idBanker` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Clients` (
  `idClients` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `Banker_idBanker` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idClients`),
  UNIQUE INDEX `idClients_UNIQUE` (`idClients` ASC) VISIBLE,
  INDEX `fk_Clients_Banker1_idx` (`Banker_idBanker` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Banker1`
    FOREIGN KEY (`Banker_idBanker`)
    REFERENCES `bank`.`Banker` (`idBanker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Accounts` (
  `idAccounts` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `balance` BIGINT ZEROFILL NOT NULL,
  `clientID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAccounts`),
  UNIQUE INDEX `idAccounts_UNIQUE` (`idAccounts` ASC) VISIBLE,
  INDEX `clientID_idx` (`clientID` ASC) VISIBLE,
  CONSTRAINT `clientID`
    FOREIGN KEY (`clientID`)
    REFERENCES `bank`.`Clients` (`idClients`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Credits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Credits` (
  `idCredits` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` BIGINT UNSIGNED NOT NULL,
  `percentage` FLOAT UNSIGNED NOT NULL,
  `paidBackAmount` BIGINT ZEROFILL UNSIGNED NOT NULL,
  `dueDate` DATE NOT NULL,
  `Accounts_idAccounts` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCredits`),
  UNIQUE INDEX `idCredits_UNIQUE` (`idCredits` ASC) VISIBLE,
  INDEX `fk_Credits_Accounts1_idx` (`Accounts_idAccounts` ASC) VISIBLE,
  CONSTRAINT `fk_Credits_Accounts1`
    FOREIGN KEY (`Accounts_idAccounts`)
    REFERENCES `bank`.`Accounts` (`idAccounts`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Cards` (
  `idCards` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Accounts_idAccounts` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCards`),
  UNIQUE INDEX `idCards_UNIQUE` (`idCards` ASC) VISIBLE,
  INDEX `fk_Cards_Accounts1_idx` (`Accounts_idAccounts` ASC) VISIBLE,
  CONSTRAINT `fk_Cards_Accounts1`
    FOREIGN KEY (`Accounts_idAccounts`)
    REFERENCES `bank`.`Accounts` (`idAccounts`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Investments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Investments` (
  `idInvestments` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` BIGINT UNSIGNED NOT NULL,
  `percentage` FLOAT UNSIGNED NOT NULL,
  `Clients_idClients` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idInvestments`),
  UNIQUE INDEX `idInvestments_UNIQUE` (`idInvestments` ASC) VISIBLE,
  INDEX `fk_Investments_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  CONSTRAINT `fk_Investments_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `bank`.`Clients` (`idClients`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
