-- MySQL Script generated by MySQL Workbench
-- Tue Dec 19 00:22:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Clients` (
  `idClients` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `monthlyIncome` INT UNSIGNED NOT NULL,
  `totalDebt` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idClients`),
  UNIQUE INDEX `idClients_UNIQUE` (`idClients` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Accounts` (
  `idAccounts` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `clientID` BIGINT UNSIGNED NOT NULL,
  `balance` BIGINT ZEROFILL NOT NULL,
  `currency` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAccounts`),
  UNIQUE INDEX `idAccounts_UNIQUE` (`idAccounts` ASC) VISIBLE,
  INDEX `clientID_idx` (`clientID` ASC) VISIBLE,
  CONSTRAINT `clientID`
    FOREIGN KEY (`clientID`)
    REFERENCES `bank`.`Clients` (`idClients`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Credits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Credits` (
  `idCredits` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` BIGINT UNSIGNED NOT NULL,
  `percentage` FLOAT UNSIGNED NOT NULL,
  `paidBackAmount` BIGINT ZEROFILL UNSIGNED NOT NULL,
  `dueDate` DATE NOT NULL,
  PRIMARY KEY (`idCredits`),
  UNIQUE INDEX `idCredits_UNIQUE` (`idCredits` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`CardType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`CardType` (
  `idCardType` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `limit` BIGINT UNSIGNED NOT NULL,
  `multicurrency` TINYINT NOT NULL,
  `exchangeFeeRate` FLOAT UNSIGNED NOT NULL,
  `creditFeeRate` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCardType`),
  UNIQUE INDEX `idCardType_UNIQUE` (`idCardType` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Cards` (
  `idCards` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Accounts_idAccounts` BIGINT UNSIGNED NOT NULL,
  `CardType_idCardType` TINYINT UNSIGNED NOT NULL,
  `isBlocked` TINYINT NOT NULL,
  `validUntil` DATE NOT NULL,
  PRIMARY KEY (`idCards`),
  UNIQUE INDEX `idCards_UNIQUE` (`idCards` ASC) VISIBLE,
  INDEX `fk_Cards_Accounts1_idx` (`Accounts_idAccounts` ASC) VISIBLE,
  INDEX `fk_Cards_CardType1_idx` (`CardType_idCardType` ASC) VISIBLE,
  CONSTRAINT `fk_Cards_Accounts1`
    FOREIGN KEY (`Accounts_idAccounts`)
    REFERENCES `bank`.`Accounts` (`idAccounts`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cards_CardType1`
    FOREIGN KEY (`CardType_idCardType`)
    REFERENCES `bank`.`CardType` (`idCardType`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Investments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Investments` (
  `idInvestments` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` BIGINT UNSIGNED NOT NULL,
  `percentage` FLOAT UNSIGNED NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `Accounts_idAccounts` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idInvestments`),
  UNIQUE INDEX `idInvestments_UNIQUE` (`idInvestments` ASC) VISIBLE,
  INDEX `fk_Investments_Accounts1_idx` (`Accounts_idAccounts` ASC) VISIBLE,
  CONSTRAINT `fk_Investments_Accounts1`
    FOREIGN KEY (`Accounts_idAccounts`)
    REFERENCES `bank`.`Accounts` (`idAccounts`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Consultants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Consultants` (
  `idConsultant` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idConsultant`),
  UNIQUE INDEX `idConsultant_UNIQUE` (`idConsultant` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`CreditRequestStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`CreditRequestStatus` (
  `idCreditRequestStatus` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCreditRequestStatus`),
  UNIQUE INDEX `idCreditRequestStatus_UNIQUE` (`idCreditRequestStatus` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`CreditRequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`CreditRequests` (
  `idCreditRequest` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Accounts_idAccounts` BIGINT UNSIGNED NOT NULL,
  `CreditRequestStatus_idCreditRequestStatus` TINYINT UNSIGNED NOT NULL,
  `Credits_idCredits` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idCreditRequest`),
  UNIQUE INDEX `idCreditRequest_UNIQUE` (`idCreditRequest` ASC) VISIBLE,
  INDEX `fk_CreditRequest_Accounts1_idx` (`Accounts_idAccounts` ASC) VISIBLE,
  INDEX `fk_CreditRequest_Credits1_idx` (`Credits_idCredits` ASC) VISIBLE,
  INDEX `fk_CreditRequests_CreditRequestStatus1_idx` (`CreditRequestStatus_idCreditRequestStatus` ASC) VISIBLE,
  CONSTRAINT `fk_CreditRequest_Accounts1`
    FOREIGN KEY (`Accounts_idAccounts`)
    REFERENCES `bank`.`Accounts` (`idAccounts`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CreditRequest_Credits1`
    FOREIGN KEY (`Credits_idCredits`)
    REFERENCES `bank`.`Credits` (`idCredits`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CreditRequests_CreditRequestStatus1`
    FOREIGN KEY (`CreditRequestStatus_idCreditRequestStatus`)
    REFERENCES `bank`.`CreditRequestStatus` (`idCreditRequestStatus`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`TransactionType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`TransactionType` (
  `idTransactionType` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `priority` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTransactionType`),
  UNIQUE INDEX `idTransactionType_UNIQUE` (`idTransactionType` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`TransactionStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`TransactionStatus` (
  `idTransactionStatus` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTransactionStatus`),
  UNIQUE INDEX `idTransactionStatus_UNIQUE` (`idTransactionStatus` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Transactions` (
  `idTransactions` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender` BIGINT UNSIGNED NOT NULL,
  `reciever` BIGINT UNSIGNED NOT NULL,
  `amount` BIGINT UNSIGNED NOT NULL,
  `TransactionType_idTransactionType` TINYINT UNSIGNED NOT NULL,
  `sendDate` DATE NOT NULL,
  `recieveDate` DATE NOT NULL,
  `fee` INT UNSIGNED NOT NULL,
  `TransactionStatus_idTransactionStatus` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTransactions`),
  UNIQUE INDEX `idTransactions_UNIQUE` (`idTransactions` ASC) VISIBLE,
  INDEX `fk_Transactions_Accounts1_idx` (`sender` ASC) INVISIBLE,
  INDEX `fk_Transactions_Accounts2_idx` (`reciever` ASC) VISIBLE,
  INDEX `fk_Transactions_TransactionType1_idx` (`TransactionType_idTransactionType` ASC) VISIBLE,
  INDEX `fk_Transactions_TransactionStatus1_idx` (`TransactionStatus_idTransactionStatus` ASC) VISIBLE,
  CONSTRAINT `fk_Transactions_Accounts1`
    FOREIGN KEY (`sender`)
    REFERENCES `bank`.`Accounts` (`idAccounts`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Accounts2`
    FOREIGN KEY (`reciever`)
    REFERENCES `bank`.`Accounts` (`idAccounts`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_TransactionType1`
    FOREIGN KEY (`TransactionType_idTransactionType`)
    REFERENCES `bank`.`TransactionType` (`idTransactionType`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_TransactionStatus1`
    FOREIGN KEY (`TransactionStatus_idTransactionStatus`)
    REFERENCES `bank`.`TransactionStatus` (`idTransactionStatus`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Clients_has_Consultants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Clients_has_Consultants` (
  `Clients_idClients` BIGINT UNSIGNED NOT NULL,
  `Consultants_idConsultant` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Clients_idClients`, `Consultants_idConsultant`),
  INDEX `fk_Clients_has_Consultants_Consultants1_idx` (`Consultants_idConsultant` ASC) VISIBLE,
  INDEX `fk_Clients_has_Consultants_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_has_Consultants_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `bank`.`Clients` (`idClients`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_has_Consultants_Consultants1`
    FOREIGN KEY (`Consultants_idConsultant`)
    REFERENCES `bank`.`Consultants` (`idConsultant`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
